import { useLocation } from 'react-router-dom';
import removeMarkdown from 'remove-markdown';
import { useNavigate } from "react-router-dom";
import config from '../config';
import { useLogsContext } from '../LogsContext';
import Create from '../components/Create2';
import { useCreateContext } from '../CreateContext';


function View() {

    const location = useLocation();
    const log = location.state?.data;

    console.log("Here I am-----");
    console.log(log);

    // log.title = '### **"Petals, Noodles, and Serenity\'s Call"**'
    const clean_title = removeMarkdown(log.title); // "Petals, Noodles, and Serenity's Call"
    const cleaner_title = clean_title.slice(1, clean_title.length-1); // get rid of the ""
    const clean_text = removeMarkdown(log.text);

    // date
    // 2025-04-27T09:47:04.270Z  ----> April 27, 2025
    const options = { year: 'numeric', month: 'long', day: 'numeric' };
    const date = new Date(log.date).toLocaleDateString('en-US', options); // log.date is a string 
    // convert it to Date object first 


    const navigate = useNavigate();
    const on_Close = () => {
        navigate('/');
    }

     // all logs
     const {setLogs} = useLogsContext();

     const {setShowCreate, setEdit_log} = useCreateContext();

    // DELETE
    const handleDelete = async() => {

        const deleted = await config.delete_log(log._id);
        if(deleted) {
            setLogs(prevLogs => prevLogs.filter(l => l._id !== log._id) );
            console.log("Log deleted");
            on_Close();
        }
        else {
            console.log("unable to delete log");
        }

    }

    // EDIT
    const handleEdit = () => {

        setShowCreate(true);
        setEdit_log(log);
        navigate('/');
        
    }

    return (
        
        <div className='p-3'>    
        <div className="container border rounded-xl custom-shadow-view-box mx-auto overflow-hidden shadow-lg flex flex-col w-4/5 sm:w-3/5 md:w-2/5 my-8 min-h-[450px] sm:min-h-[400px] max-h-[90vh] relative">
        {/* container border rounded-xl custom-shadow-view-box mx-auto overflow-hidden shadow-lg flex flex-col w-4/5 sm:w-3/5 md:w-2/5 min-h-[350px] sm:min-h-[200px] max-h-[90vh] my-8 relative */}
    {/*    */}
        {/* Title */}
        <div className="flex-[1] title-container border-b rounded-t-xl text-center font-extrabold text-3xl sm:text-2xl bg-[#DE92D0]  relative flex justify-between items-center gap-10">
          {/* Left spacer to help center the title */}
            <div className="w-8 sm:w-10"></div>
             <span className='p-1'>{cleaner_title}</span>
            <i onClick={on_Close} className="close-btn fa-solid fa-xmark text-black p-3 cursor-pointer text-right"></i>
           
        </div>
        {/* absolute top-2 right-2  */}
        {/* Main Content */}
        <div className="flex-[10] content-container p-4 text-justify bg-white relative overflow-hidden">
            <p className="content-text text-lg sm:text-md md:text-lg custom-scroll overflow-y-auto">{clean_text}</p>
            <span className="content-date absolute right-3 bottom-2 text-sm text-gray-600">{`[${date}]`}</span>
        </div>
    
        {/* Footer Section */}
        <div className="flex-[1] footer-container border-t rounded-b-xl flex justify-between sm:justify-center items-center bg-[#DE92D0] p-2">
            <p className="footer-text text-md sm:text-sm">{"Generated by AI ;)"}</p>
            <div className="action-buttons absolute right-0 flex flex-col sm:flex-row items-center gap-3">
                <button onClick={handleDelete} className="delete-btn cursor-pointer"><i className="fa-solid fa-trash text-3xl"></i></button>
                <button onClick={handleEdit} className="edit-btn cursor-pointer"><i className="fa-solid fa-pen text-3xl"></i></button>
            </div>
        </div>
    </div>
    </div>
    
       
    )

}
export default View;

//  mt-10 relative