import { useLocation } from 'react-router-dom';
import removeMarkdown from 'remove-markdown';
import { useNavigate } from "react-router-dom";
import config from '../config';
import { useLogsContext } from '../LogsContext';
import Create from '../components/create2';
import { useCreateContext } from '../CreateContext';


function View() {

    const location = useLocation();
    const log = location.state?.data;

    console.log("Here I am-----");
    console.log(log);

    // log.title = '### **"Petals, Noodles, and Serenity\'s Call"**'
    const clean_title = removeMarkdown(log.title); // "Petals, Noodles, and Serenity's Call"
    const cleaner_title = clean_title.slice(1, clean_title.length-1); // get rid of the ""
    const clean_text = removeMarkdown(log.text);

    // date
    // 2025-04-27T09:47:04.270Z  ----> April 27, 2025
    const options = { year: 'numeric', month: 'long', day: 'numeric' };
    const date = new Date(log.date).toLocaleDateString('en-US', options); // log.date is a string 
    // convert it to Date object first 


    const navigate = useNavigate();
    const on_Close = () => {
        navigate('/');
    }

     // all logs
     const {setLogs} = useLogsContext();

     const {setShowCreate, setEdit_log} = useCreateContext();

    // DELETE
    const handleDelete = async() => {

        const deleted = await config.delete_log(log._id);
        if(deleted) {
            setLogs(prevLogs => prevLogs.filter(l => l._id !== log._id) );
            console.log("Log deleted");
            on_Close();
        }
        else {
            console.log("unable to delete log");
        }

    }

    // EDIT
    const handleEdit = () => {

        setShowCreate(true);
        setEdit_log(log);
        navigate('/');
        
    }

    return (
        <div className='w-full h-full sm:h-auto mx-auto mt-20 p-4 flex justify-center items-center'>
            
            <div className="border rounded-2xl overflow-hidden custom-shadow-view-box flex flex-col w-3/5 sm:w-4/5 md:w-3/5 min-h-[400px] sm:min-h-[300px] max-h-[90vh] sm:max-h-[80vh] mt-10 relative  ">
            <i onClick={on_Close} className="fa-solid fa-xmark text-black absolute top-2 right-2 p-2 cursor-pointer"></i>
                <div className="flex-[1] border-b rounded-t-2xl text-center font-extrabold text-3xl md:text-2xl sm:text-xl  bg-[#DE92D0] p-2">{cleaner_title}</div>
                <div className="flex-[10] p-3 text-justify text-xl bg-white relative">
                    <p className='p-4 sm:max-h-[500px]  custom-scroll overflow-y-auto lg:overflow-hidden'>{clean_text}</p>
                    <span className='absolute right-0 m-3'>{`[${date}]`}</span>
                </div>
                <div className=" flex-[1] border-t rounded-b-2xl flex justify-center items-center relative bg-[#DE92D0] p-3">
                    <p className="">{"Generated by AI ;)"}</p>
                    <div className="absolute right-0  flex items-center gap-4 p-5">
                        <button onClick={handleDelete} className="cursor-pointer"><i className="fa-solid fa-trash text-3xl"></i></button>
                        <button onClick={handleEdit} className="cursor-pointer"><i className="fa-solid fa-pen text-3xl"></i></button>
                    </div>
                </div>
            </div>
        </div>
    )

}
export default View;

//  mt-10 relative